CREATE TABLE apostas (
    id BIGINT PRIMARY KEY,
    time VARCHAR(50) NOT NULL,
    valor_aposta DOUBLE PRECISION NOT NULL,
    odd DOUBLE PRECISION NOT NULL,
    data_aposta TIMESTAMP NOT NULL
);

CREATE SEQUENCE apostas_seq START WITH 1 INCREMENT BY 1;